// Hardcoded mock bookings for the admin dashboard.
export const bookings = [
  {
    id: "BC-2041",
    guest: "Giulia Conti",
    stay: "Villa Santa Maria, vista sull'isola",
    location: "Tropea",
    checkIn: "2026-07-10",
    checkOut: "2026-07-14",
    nights: 4,
    guests: 4,
    total: 1165,
    status: "Confermata",
  },
  {
    id: "BC-2042",
    guest: "Marco De Luca",
    stay: "Suite con piscina a Capo Vaticano",
    location: "Ricadi",
    checkIn: "2026-07-18",
    checkOut: "2026-07-22",
    nights: 4,
    guests: 2,
    total: 1321,
    status: "Confermata",
  },
  {
    id: "BC-2043",
    guest: "Sara Greco",
    stay: "Casa di pescatori a Chianalea",
    location: "Scilla",
    checkIn: "2026-08-01",
    checkOut: "2026-08-05",
    nights: 4,
    guests: 3,
    total: 765,
    status: "In attesa",
  },
  {
    id: "BC-2044",
    guest: "Luca Ferrari",
    stay: "Chalet sul Lago Arvo, Lorica",
    location: "Sila",
    checkIn: "2026-08-08",
    checkOut: "2026-08-12",
    nights: 4,
    guests: 5,
    total: 610,
    status: "Confermata",
  },
  {
    id: "BC-2045",
    guest: "Elena Russo",
    stay: "Villa fronte Isola di Dino",
    location: "Praia a Mare",
    checkIn: "2026-06-20",
    checkOut: "2026-06-27",
    nights: 7,
    guests: 8,
    total: 1580,
    status: "Completata",
  },
  {
    id: "BC-2046",
    guest: "Antonio Bruno",
    stay: "Loft sul lungomare di Reggio",
    location: "Reggio Calabria",
    checkIn: "2026-09-02",
    checkOut: "2026-09-05",
    nights: 3,
    guests: 2,
    total: 405,
    status: "In attesa",
  },
  {
    id: "BC-2047",
    guest: "Chiara Esposito",
    stay: "Appartamento nel palazzo storico",
    location: "Gerace",
    checkIn: "2026-05-30",
    checkOut: "2026-06-02",
    nights: 3,
    guests: 2,
    total: 330,
    status: "Annullata",
  },
];
