export const offers = [
  {
    slug: "tropea-3-notti",
    title: "Tropea, 3 notti sul mare",
    location: "Costa degli Dei",
    nights: 3,
    oldPrice: 540,
    price: 399,
    discount: 26,
    badge: "Best seller",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Santa_Maria_dell%27Isola_-_Tropea_-_Calabria_-_Italy_-_July_17th_2013_-_01.jpg/1920px-Santa_Maria_dell%27Isola_-_Tropea_-_Calabria_-_Italy_-_July_17th_2013_-_01.jpg",
    perks: ["Villa vista mare", "Colazione inclusa", "Tour in barca"],
  },
  {
    slug: "settimana-sila",
    title: "Settimana verde in Sila",
    location: "Lorica · Parco della Sila",
    nights: 7,
    oldPrice: 910,
    price: 690,
    discount: 24,
    badge: "Natura",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Lago_Arvo%2C_Sila%2C_localit%C3%A0_Lorica.jpg/1920px-Lago_Arvo%2C_Sila%2C_localit%C3%A0_Lorica.jpg",
    perks: ["Chalet sul lago", "Trekking guidato", "Prodotti tipici"],
  },
  {
    slug: "weekend-scilla",
    title: "Weekend a Scilla",
    location: "Costa Viola",
    nights: 2,
    oldPrice: 310,
    price: 239,
    discount: 23,
    badge: "Romantico",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Chianalea_di_Scilla_-_panoramio.jpg/1920px-Chianalea_di_Scilla_-_panoramio.jpg",
    perks: ["Casa a Chianalea", "Cena di pesce spada", "Aperitivo al tramonto"],
  },
  {
    slug: "capo-vaticano-spa",
    title: "Capo Vaticano Spa & Relax",
    location: "Ricadi",
    nights: 4,
    oldPrice: 1160,
    price: 890,
    discount: 23,
    badge: "Premium",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Ricadi_-_Capo_Vaticano_-_05.jpg/1280px-Ricadi_-_Capo_Vaticano_-_05.jpg",
    perks: ["Suite con piscina", "Percorso Spa", "Mezza pensione"],
  },
  {
    slug: "borghi-pollino",
    title: "Borghi del Pollino",
    location: "Morano Calabro",
    nights: 3,
    oldPrice: 360,
    price: 270,
    discount: 25,
    badge: "Borghi",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Morano_Calabro_Panorama_%28Particolare_001%29.jpg/1280px-Morano_Calabro_Panorama_%28Particolare_001%29.jpg",
    perks: ["Casa in pietra", "Gole del Raganello", "Degustazione"],
  },
  {
    slug: "magna-grecia-reggio",
    title: "Sulle tracce della Magna Grecia",
    location: "Reggio Calabria",
    nights: 3,
    oldPrice: 430,
    price: 329,
    discount: 23,
    badge: "Cultura",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Reggio_Calabria_-_Lungomare_Falcomat%C3%A0_-_6.jpg/1280px-Reggio_Calabria_-_Lungomare_Falcomat%C3%A0_-_6.jpg",
    perks: ["Loft sul lungomare", "Bronzi di Riace", "Bergamotto experience"],
  },
];
